### ISSUE TITLE
寻求商务课程合作

### ISSUE THREAD

**Issue by specialzxw** [livelyPeng/pl-drag-template#3]
您好，我们对您分享的这个项目十分感兴趣，想要与您进行课程合作，可以留下您的邮箱或微信联系方式，方便我们与您建立联系吗？

**Comment by livelyPeng** [comment]
18708188670

**Comment by specialzxw** [comment]
> 18708188670

合作事宜比较复杂，电话联系可能无法一时之间讲清楚，为避免耽误您太多时间，方便留下您的微信或邮箱建立联系吗，也欢迎您直接添加我的微信了解  `shiyanloukecheng` 。

**Comment by livelyPeng** [comment]
travel196这是微信



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "specialzxw"<notifications@github.com&gt;; 
发送时间: 2020年7月24日(星期五) 上午10:53
收件人: "livelyPeng/pl-drag-template"<pl-drag-template@noreply.github.com&gt;; 
抄送: "Simple love"<403802162@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [livelyPeng/pl-drag-template] 寻求商务课程合作 (#3)





  
18708188670
  
合作事宜比较复杂，电话联系可能无法一时之间讲清楚，为避免耽误您太多时间，方便留下您的微信或邮箱建立联系吗，也欢迎您直接添加我的微信了解  shiyanloukecheng 。
